/*
 * Attacker.java
 *
 * Created on __DATE__, __TIME__
 */

package com.mis.gui;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Enumeration;
import java.util.Properties;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

import org.jvnet.substance.SubstanceLookAndFeel;

import com.mis.actions.AttackRx;
import com.mis.actions.Control;
import com.mis.actions.Data;

/**
 * 
 * @author __USER__
 */
public class Attacker extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	int port;

	/** Creates new form Attacker */
	public Attacker() {
		initComponents();
		init();
	}

	private void init() {
		// TODO Auto-generated method stub
		port = 1267;
		new AttackRx(this, port);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtForgeIP = new javax.swing.JTextField();
		btnGetDataInfor = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblInfor = new javax.swing.JTable();
		jLabel3 = new javax.swing.JLabel();
		txtRouter = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		txtInitTTL = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txtDestIP = new javax.swing.JTextField();
		txtTTL = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtaData = new javax.swing.JTextArea();
		btnAttck = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jLabel1.setText("Enter Forge IP");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(20, 220, 100, 14);
		getContentPane().add(txtForgeIP);
		txtForgeIP.setBounds(100, 220, 170, 20);

		btnGetDataInfor.setText("Get Datatrafer Information");
		btnGetDataInfor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGetDataInforActionPerformed(evt);
			}
		});
		getContentPane().add(btnGetDataInfor);
		btnGetDataInfor.setBounds(350, 30, 240, 30);

		jLabel2.setText("Data");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(20, 340, 80, 14);

		dftPackinfor = new DefaultTableModel();
		tblInfor.setModel(dftPackinfor);
		jScrollPane1.setViewportView(tblInfor);

		dftPackinfor.addColumn("Source IP");
		dftPackinfor.addColumn("Destination IP");
		dftPackinfor.addColumn("Next Router");
		dftPackinfor.addColumn("Initial TTL");
		dftPackinfor.addColumn("TTL");
		dftPackinfor.addColumn("Data");

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(20, 70, 580, 130);

		jLabel3.setText("Enter Router");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(30, 40, 110, 14);
		getContentPane().add(txtRouter);
		txtRouter.setBounds(140, 40, 160, 20);

		jLabel4.setText("Destination");
		getContentPane().add(jLabel4);
		jLabel4.setBounds(290, 220, 70, 14);

		jLabel5.setText("Initial TTL");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(20, 260, 70, 14);
		getContentPane().add(txtInitTTL);
		txtInitTTL.setBounds(100, 260, 170, 20);

		jLabel6.setText("TTL");
		getContentPane().add(jLabel6);
		jLabel6.setBounds(290, 260, 60, 14);
		getContentPane().add(txtDestIP);
		txtDestIP.setBounds(370, 220, 160, 20);
		getContentPane().add(txtTTL);
		txtTTL.setBounds(370, 260, 160, 20);

		jtaData.setColumns(20);
		jtaData.setRows(5);
		jScrollPane2.setViewportView(jtaData);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(100, 300, 166, 96);

		btnAttck.setText("Attack");
		btnAttck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAttckActionPerformed(evt);
			}
		});
		getContentPane().add(btnAttck);
		btnAttck.setBounds(320, 300, 210, 100);

		setSize(650, 480);
		setTitle("Attacker::");
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnAttckActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Data data = new Data();
		data.sourceIP = txtForgeIP.getText();
		data.initTTL = Integer.parseInt(txtInitTTL.getText());
		data.TTL = Integer.parseInt(txtTTL.getText());
		data.destiIP = txtDestIP.getText();
		data.reqData = jtaData.getText();
		data.routers = getRouters();
		data.sourceport = port;

		int port = action.getPort(txtRouter.getText());
		try {

			Socket socket = new Socket("localhost", port);
			ObjectOutputStream oos = new ObjectOutputStream(socket
					.getOutputStream());
			oos.writeObject("Req");
			oos.writeObject(data);
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private Vector<String> getRouters() {
		// TODO Auto-generated method stub
		Vector<String> vec = new Vector<String>();
		String myrouter = txtRouter.getText();
		boolean flag = false;
		try {
			Properties properties = new Properties();
			FileInputStream fis = new FileInputStream("Router.properties");
			properties.load(fis);
			fis.close();
			Enumeration<Object> em = properties.keys();
			while (em.hasMoreElements()) {
				String key = (String) em.nextElement();
				if (key.equals(myrouter))
					flag = true;
				if (flag)
					vec.add(key);
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return vec;
	}

	private void btnGetDataInforActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int port = action.getPort(txtRouter.getText());
		try {

			Socket socket = new Socket("localhost", port);
			ObjectOutputStream oos = new ObjectOutputStream(socket
					.getOutputStream());
			oos.writeObject("aReq");
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		JFrame.setDefaultLookAndFeelDecorated(true);
		SubstanceLookAndFeel
				.setCurrentTheme("org.jvnet.substance.theme.SubstanceCharcoalTheme");
		SubstanceLookAndFeel
				.setCurrentButtonShaper("org.jvnet.substance.button.StandardButtonShaper");

		SubstanceLookAndFeel
				.setCurrentGradientPainter("SpecularGradientPainter");
		try {
			UIManager.setLookAndFeel(new SubstanceLookAndFeel());
		} catch (UnsupportedLookAndFeelException e) {

			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Attacker().setVisible(true);
			}
		});
	}

	Control action = new Control();
	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAttck;
	private javax.swing.JButton btnGetDataInfor;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jtaData;
	private javax.swing.JTable tblInfor;
	private javax.swing.JTextField txtDestIP;
	private javax.swing.JTextField txtForgeIP;
	private javax.swing.JTextField txtInitTTL;
	private javax.swing.JTextField txtRouter;
	private javax.swing.JTextField txtTTL;
	public DefaultTableModel dftPackinfor;
	// End of variables declaration//GEN-END:variables

}