/*
 * Router.java
 *
 * Created on __DATE__, __TIME__
 */

package com.mis.gui;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

import org.jvnet.substance.SubstanceLookAndFeel;

import com.mis.actions.BGPRouterRx;
import com.mis.actions.Control;

/**
 * 
 * @author __USER__
 */
public class BGPRouter extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Control action;
	String router;

	/** Creates new form Router */
	public BGPRouter() {
		initComponents();
		init();
	}

	private void init() {
		// TODO Auto-generated method stub
		action = new Control();
		router = action.getRouter();
		setTitle(router);
		int port = action.getPort();
		action.setProperty("Router.properties", router, "" + port);
		new BGPRouterRx(this, port, action);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tblPackInfor = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		btnExit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		dftPackinfor = new DefaultTableModel();
		tblPackInfor.setModel(dftPackinfor);
		jScrollPane1.setViewportView(tblPackInfor);

		dftPackinfor.addColumn("Source IP");
		dftPackinfor.addColumn("Destination IP");
		dftPackinfor.addColumn("Next Router");
		dftPackinfor.addColumn("Initial TTL");
		dftPackinfor.addColumn("TTL");
		dftPackinfor.addColumn("Data");

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(30, 110, 600, 180);

		jLabel1.setText("Packet Forwarding Information");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(30, 90, 210, 14);

		btnExit.setText("Exit");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});
		getContentPane().add(btnExit);
		btnExit.setBounds(520, 300, 110, 30);

		setSize(660, 400);
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		JFrame.setDefaultLookAndFeelDecorated(true);
		SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceAquaTheme");
		SubstanceLookAndFeel
				.setCurrentButtonShaper("org.jvnet.substance.button.StandardButtonShaper");
		
		SubstanceLookAndFeel
				.setCurrentGradientPainter("SpecularGradientPainter");
		try {
			UIManager.setLookAndFeel(new SubstanceLookAndFeel());
		} catch (UnsupportedLookAndFeelException e) {

			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BGPRouter().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnExit;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblPackInfor;
	public DefaultTableModel dftPackinfor;
	// End of variables declaration//GEN-END:variables

}